#!/bin/sh
#/***********************************************************************
#* copyright (c) 2004 MALET Jean-luc aka cityhunter
#* This program is free software; you can redistribute it and/or modify
#* it under the terms of the artistic license as published in the top source dir of the
#* package
#************************************************************************/
#the 2s sleep is needed because it seems that the setup of cryptdevice takes too long...
/sbin/modprobe dm_crypt &&
/sbin/modprobe aes &&
sleep 2s &&
if [ -f key.key ]; then
	for DISKS in $(cat /etc/cryptdevice); do
		for DISK in $(ls /dev | grep $DISKS); do
			cryptsetup -c aes -f key.key create $DISK /dev/$DISK &&
			echo $DISK >> /tmp/cryptdevs
		done
	done
fi
